Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,9 +23,18 @@ jobs:
 
       - name: Upload Test Results to Netlify
         run: |
-          curl -X POST -F "file=@cypress/results/test-results.json" https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys --header "Authorization: Bearer ${{ secrets.NETLIFY_API_KEY }}"
+          curl -X POST -F "file=results/test-results.json" https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys --header "Authorization: Bearer ${{ secrets.NETLIFY_API_KEY }}"
         continue-on-error: true
-          
+
+      - name: Check if test-results.json exists
+        run: |
+          if [ -f cypress/results/test-results.json ]; then
+            echo "test-results.json found!"
+          else
+            echo "test-results.json not found."
+            exit 1
+          fi
+
   deploy:
     runs-on: ubuntu-latest
     needs: cypress-run
